### PR TITLE
Add ability to extend classes

### PR DESCRIPTION
**Pull request by loicbenoit**
Proposed backward compatible implementation for allowing users to extend the plugin's classes. Not all classes can be extended, only those listed in setup.php.

See https://github.com/pluginsGLPI/genericobject/issues/230

### CODE REVIEW

**Review by FVallieres — APPROVED** [review]

**Comment by FVallieres** [comment]
Please resolve conflicts .

**Comment by loicbenoit** [comment]
I don't have permissions to view the conflicts or don't know how. Can you help?

image

**Comment by loicbenoit** [comment]
These are the only two conflicts that I see, but these are also changes that I want to submit to the community.

image

image

Reasonning is explained in ticket: https://github.com/pluginsGLPI/genericobject/issues/230

**Review by FVallieres — APPROVED** [review]

**Review by FVallieres — APPROVED** [review]

**Review by FVallieres — APPROVED** [review]

**Review by lzeptile — APPROVED** [review]

**Review by FVallieres — APPROVED** [review]

**Comment by loicbenoit** [comment]
Replaced by https://github.com/VilledeMontreal/genericobject/pull/6

**Pull request closed without merging**
